### ISSUE TITLE
Also unlink workflow on [pre]uninstall?

### ISSUE THREAD

**Issue by danielbayley** [SamVerschueren/alfred-link#10]
Since npm `preuninstall` runs before any modules actually get removed, and this package already has knowledge of where the link was created (using _resolve-alfred-prefs_), I thought it would be useful if it could also remove the link it created…

Something like `"preuninstall": "alfred-unlink"` maybe?

At the moment I am doing this by including a `lib/unlink.js` with the workflow and calling that from `"preuninstall": "lib/unlink.js"`:

``` js
const fs = require('fs');
const resolve = require('resolve-alfred-prefs');
resolve().then(path => {
  return fs.unlink(`${path}/workflows/${process.env.npm_package_name}`);
});
```

But this seems a bit silly just to remove a symlink…

**Comment by SamVerschueren** [comment]
It's a symlink so it's not necessary to clean it up as it will be removed automatically. I just tested it and after uninstalling `npm run alfred-ng2` and opening the Alfred preferences, that workflow was removed automatically. That's how a symlink works :).

**Comment by danielbayley** [comment]
> That's how a symlink works

@SamVerschueren Actually I'm pretty sure that's how a _hardlink_ works as opposed to a symlink, which always points to a specific location whether it exists or not, and is unaffected by the removal of the item it points to (which is often handy).

Ah, so I was looking at the file system while testing rather than opening Alfred preferences, so although you're correct about Alfred removing the workflow, the [broken] symlink still actually remains in the workflows directory (at least for me… but I'm betting it's the same on your machine if you check?)

**Comment by SamVerschueren** [comment]
Let me reopen then. Haven't checked the filesystem to be honest. Will try to look into this when I find some more time.

**Comment by SamVerschueren** [comment]
Released in `0.2.0`. You can now add `alfred-unlink` to your `preuninstall` hook and it will remove the symlink. It will also clean up the cache and config data from that workflow so no data is left behind :).

On a sidenote, if you're using `alfy`, use `alfy-init` as `postinstall` hook and `alfy-cleanup`. At the moment of writing this, `alfy-cleanup` is not yet added to `alfy` but I will file a PR now.

The reason it's best practice to use these is that `alfy` might add extra features in the future on init or on cleanup.

**Comment by danielbayley** [comment]
@SamVerschueren Ah cool; I will check it out… I can trim my codebase a little 👍 

I'm not actually using `alfy` but will probably try it out as I have half a dozen other workflows planned!

**Comment by SamVerschueren** [comment]
> I'm not actually using alfy but will probably try it out as I have half a dozen other workflows planned!

It has some cool features built in like caching, update notifications, etc.
