### ISSUE TITLE
script alfred-unlink command not found

### ISSUE THREAD

**Issue by LitoMore** [SamVerschueren/alfred-link#14]
- node version:  v7.9.0
- npm version: 4.6.1

## Expected behavior

Both `alfred-link` and `alfred-unlink` scripts works

## Actual behavior

`alfred-link` can work, but `alfred-unlink` cannot work

## How to reproduce

Install && Uninstall

```bash
$ npm install -g alfred-fanfou@0.0.2
# Then
$ npm uninstall -g alfred-fanfou
```

Output:

```
> alfred-fanfou@0.0.2 preuninstall /Users/litomore/.nvm/versions/node/v7.9.0/lib/node_modules/alfred-fanfou
> alfred-unlink

sh: alfred-unlink: command not found
npm WARN lifecycle alfred-fanfou@0.0.2~preuninstall: continuing anyway alfred-fanfou@0.0.2 preuninstall: `alfred-unlink`
npm WARN lifecycle spawn ENOENT
```

> My code is here: https://github.com/LitoMore/alfred-fanfou/tree/370fb346922caae5b96aab3f3e88449a02c52815

**Comment by SamVerschueren** [comment]
I can't test it right now but it should work so no idea why it's failing. I'd also suggest using [alfy](https://github.com/sindresorhus/alfy) which embeds all of this and is super easy to use.

**Comment by LitoMore** [comment]
@SamVerschueren alfy's `alfy-cleanup` cannot work either.

**Comment by SamVerschueren** [comment]
I investigated this as I was almost sure it worked. Apparently, this seems to be a bug in npm itself. It's tracked by https://github.com/npm/npm/issues/11894. I created a reproduction repository and responded to the thread https://github.com/npm/npm/issues/11894#issuecomment-303513224. So nothing I can really do about it. Thanks for reporting!

**Comment by LitoMore** [comment]
Thank you!
