### ISSUE TITLE
Support for private packages

### ISSUE THREAD

**Issue by nicohaemhouts** [SamVerschueren/alfred-link#15]
Hey, great package! I'm using it to create an Alfred Workflow to use at work. We use private packages, but private npm packages have a forward slash `/` in their package name. Example `@my-company/my-alfred-workflow`. When trying to `symlink` this will try to create a link to a path that doesn't exist. Example `~/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/@my-company/my-alfred-workflow`. 

If you use something like https://www.npmjs.com/package/sanitize-filename on the package name this problem should be resolved.

**Comment by sindresorhus** [comment]
We could also use https://github.com/sindresorhus/filenamify, but I think just converting the `/` to `-` should be enough as package names are filename safe otherwise.

**Comment by SamVerschueren** [comment]
Jup, agree with replacing `/` with `-`.

**Comment by nicohaemhouts** [comment]
Cool, one PR coming up!
