### ISSUE TITLE
add -f, --force option

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/alfred-link#4]
I guess it would be nice to add a `-f`/`--force` option that will bypass the [--global](https://github.com/SamVerschueren/alfred-link/blob/master/cli.js#L6) check.

Or don't check for the `--global` flag if `alfred-link` was called directly instead of through an npm script.

**Comment by sindresorhus** [comment]
> Or don't check for the --global flag if alfred-link was called directly instead of through an npm script.

👍
