### ISSUE TITLE
`webaddress` should be `repository` or `homepage`, not `author.url`

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/alfred-link#5]
You should also probably use [`read-pkg-up`](https://github.com/sindresorhus/read-pkg-up) so you get the normalized package.json data.

**Comment by sindresorhus** [comment]
Actually, if you use `read-pkg-up` you can just use `homepage` as `repository` is used if it's not set.

**Comment by SamVerschueren** [comment]
And fallback to `author.url` if `homepage` or `repository` is not set?

**Comment by sindresorhus** [comment]
Sure
