### ISSUE TITLE
Better story for developing a workflow

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/alfred-link#6]
Currently I have to run `npm install --global .` each time I do a change. That is sub-optimal. We should figure out a better process for developing a workflow.

**Comment by SamVerschueren** [comment]
You can just run `alfred-link` once inside the development directory, no? Haven't tried it but I guess it should work.

**Comment by sindresorhus** [comment]
Ah yeah, works. Should documented though.

**Comment by sindresorhus** [comment]
Actually, not perfectly. If I run `alfred-link`, it rewrites info.plist. There should be a way to have it not rewrite, either automatic or through a flag.

**Comment by SamVerschueren** [comment]
If it doesn't update `info.plist`, it won't have a name in alfred. Not sure if it can handle that? It's perfectly possible to only update `info.plist` if the package was installed through `npm install -g`.

**Comment by sindresorhus** [comment]
Alfred glitches hard without a name. Maybe we should just hardcode the name in `info.plist` too? That tiny duplication will make it a lot easier to work on plugins. Only `name` is required.

**Comment by SamVerschueren** [comment]
Good point. I will drop the `name` transformation then in `alfred-link` and won't transform `info.plist` if `alfred-link` was called directly.

**Comment by SamVerschueren** [comment]
@sindresorhus Clear enough? https://github.com/SamVerschueren/alfred-link#development
