### ISSUE TITLE
What to do if a workflow with that name already exists?

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/alfred-link#7]
I once had two workflows with the same name. Alfred preferences literally hung with a white screen because of this. Should we prevent this from happening by checking if a workflow with that name already exists? This means that we will have to iterate all the workflows, parse the `info.plist` file and extract the `name` property from it.

`alfred-link` already prevents this somewhat if the destination directory already exists. It removes that directory and creates a new symlink (see [code](https://github.com/SamVerschueren/alfred-link/blob/master/lib/link.js#L8)). But this does not cover the case if someone installed a workflow through packal with the name `ng2` (which has a uuid as directory name) and through `npm install -g alfred-ng2` (which uses `ng2`) as directory name.

**Comment by sindresorhus** [comment]
I think we should prevent this from happening. Even though it's an edge-case, it's very hard for a user to debug what's wrong and fix it when Alfred hangs. To improve performance, you could adapt my previous [regex to workflow version](https://github.com/sindresorhus/alfy/commit/de7728944f64c2040ae5d8ebca6a3c10ce68ed42#diff-168726dbe96b3ce427e7fedce31bb0bcL29), to parse workflow name instead. This happens during install anyways, so npm will be way slower than the one extra second we use to parse all the names.

**Comment by SamVerschueren** [comment]
> it's very hard for a user to debug what's wrong and fix it when Alfred hangs

Exactly, it took me almost half an hour to figure this out.

> To improve performance, you could adapt my previous regex to workflow version, to parse workflow name instead.

Good point! The reason I was having some doubts about this was because of the parsing.

**Comment by SamVerschueren** [comment]
Strange, I was implementing this and Alfred seems to have fixed this issue. So not sure if I should still fix it here.

**Comment by sindresorhus** [comment]
What happens now when there are two workflows with the same name?

**Comment by SamVerschueren** [comment]
Nothing, it just works, even with the same bundle id.

**Comment by sindresorhus** [comment]
I guess this can be closed then.
